### ISSUE TITLE
Pages Site Suggestion.

### ISSUE THREAD

**Issue by himanshupal** [stc/HackPact#1]
# Hey! There.
I wanna say that you have done a wonderful work of compiling these experiments but it would be far better for everyone to see and understand your experimentation, if you have a [Github Pages](https://pages.github.com) site associated with it and provide its link in [readme](https://github.com/stc/HackPact/blob/master/README.md).
I see that you have already included an [Index](https://github.com/stc/HackPact/blob/master/index.html) page at every stage of your project, so its just a matter of configuring it in repo settings........

### Please ignore & provide me with the link if it already has a website associated with it.

**Comment by stc** [comment]
hi there,
thanks for suggesting, in fact you can find every living piece at
https://stc.github.io/HackPact/

hope you enjoy playing around with them

yours,
Agoston

**Comment by himanshupal** [comment]
Thanks, Agoston.
